### ISSUE TITLE
上传文件里的变量，构建后重写成死数据

### ISSUE THREAD

**Issue by lionel126** [onloadcc/qiniu-file#2]
文件夹路径/bucket/链接文件这些使用了变量，比如${VersionName}，构建时VersionName是1.0。
构建完成后，变量都写死成了1.0。

下次我传变量没什么作用了

**Comment by onloadcc** [comment]
哦。是有这个问题，我看下怎么处理。

**Comment by onloadcc** [comment]
问题已修改  @lionel126
